spring:
  application:
    name: boasaude

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework: ERROR
      hibernate: ERROR
    com:
      oktech:
        boasaude: ERROR

jwt:
  secret: mysecret
