spring:
  application:
    name: boasaude

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework: ERROR
    org.hibernate: ERROR
    com.oktech.boasaude: ERROR
